---
resources:
# The repo with our Dockerfile
- name: vijay-ci
  type: git
  icon: github
  source:
    uri: https://github.com/vijaykothareddy/ci.git
    branch: master

# Where we will push the image
- name: ecr-docker-reg
  type: docker-image
  source:
    aws_access_key_id: ((aws-token))
    aws_secret_access_key: ((aws-secret))
    repository: ((aws-repo))


jobs:
- name: build-and-push
  plan:
  - get: vijay-ci
  - get: ecr-docker-reg
  
  - task: build
    image: ecr-docker-reg
    file: vijay-ci/tasks/build.yml
    params: 
      aws_access_key_id: ((aws-token))
      aws_secret_access_key: ((aws-secret))
      aws_default_region: ap-southeast-2


