---
resources:
# The repo with our Dockerfile
- name: vijay-ci
  type: git
  icon: github
  source:
    uri: https://github.com/vijaykothareddy/ci.git
    branch: master

# Where we will push the image
- name: ecr-docker-reg
  type: registry-image
  source:
    aws_access_key_id: ((aws-token))
    aws_secret_access_key: ((aws-secret))
    repository: ((aws-repo))


jobs:
- name: build-and-push
  plan:
  - get: vijay-ci
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: vijay-ci
      outputs:
      - name: image
      params:
        CONTEXT: ci/Dockerfiles/simple
      run:
        path: build
  - put: simple-image
    params:
      image: image/image.tar


